ethercat:
  master_id: 0
  esi: /home/pierre/Dev/Ethercat/ethercat_controller/config/esi/epos-3axis.xml

slaves:
  - !Epos
    id: 0
    reduction: 4.0
    encoder_resolution: 4096
  - !Epos
    id: 1
    reduction: 2.0
    encoder_resolution: 2048
  - !Epos
    id: 2
    reduction: 3.0
    encoder_resolution: 4096