ethercat:
  master_id: 0
  esi: esi/orbitas.xml
  cycle_time_ms: 1 # ms

slaves:
  - !Poulpe
    id: 0
    orbita_type: 3
    name: "RightWristOrbita3d"
  - !Poulpe
    id: 1
    orbita_type: 3
    name: "NeckOrbita3d"
