[package]
name = "poulpe_ethercat_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
num = "0.4.0"
num-traits = "0.2.15"
num-derive = "0.3.3"
ethercat_controller = { path = "../ethercat_controller" }
log = "0.4.17"
env_logger = "0.9.0"

